-- Write your PostgreSQL query statement below
WITH BASE AS (
SELECT
    NUM,
    LAG(NUM, 1) OVER (ORDER BY ID) AS NUM_LAG1,
    LAG(NUM, 2) OVER (ORDER BY ID) AS NUM_LAG2
FROM
    LOGS
)
SELECT 
    DISTINCT NUM AS CONSECUTIVENUMS
FROM
    BASE
WHERE
    ( NUM = NUM_LAG1 AND NUM_LAG1 = NUM_LAG2)