# Write your MySQL query statement below
WITH BASE_DRK AS (
    SELECT
        NAME,
        SALARY,
        DEPARTMENTID,
        DENSE_RANK() OVER (
            PARTITION BY DEPARTMENTID
            ORDER BY SALARY DESC
        ) RK
      FROM EMPLOYEE
)
SELECT
    D.NAME AS DEPARTMENT,
    BD.NAME AS EMPLOYEE,
    BD.SALARY
  FROM BASE_DRK BD
  LEFT JOIN DEPARTMENT D
    ON BD.DEPARTMENTID = D.ID
 WHERE BD.RK <= 3