/*
 * 날짜가 연속적으로 존재하지 않는 날도 고려해야 함
 */
WITH BASE AS (
SELECT
    ID,
    RECORDDATE,
    TEMPERATURE,
    LAG(RECORDDATE, 1) OVER (ORDER BY RECORDDATE) AS RECORDDATE_LAG1,
    LAG(TEMPERATURE, 1) OVER (ORDER BY RECORDDATE) AS TEMPERATURE_LAG1
FROM 
    WEATHER
)
SELECT
    ID
FROM
    BASE
WHERE
    TEMPERATURE > TEMPERATURE_LAG1
AND
    RECORDDATE = RECORDDATE_LAG1 + INTERVAL '1 DAY'