WITH CNT_EMPLOYEE_BY_MANAGER AS (
    SELECT
        MANAGERID,
        COUNT(*) AS CNT_EMPLOYEE
    FROM EMPLOYEE
    WHERE MANAGERID IS NOT NULL
    GROUP BY MANAGERID
)
SELECT
    E.NAME
FROM EMPLOYEE E
JOIN CNT_EMPLOYEE_BY_MANAGER C
  ON E.ID = C.MANAGERID
WHERE C.CNT_EMPLOYEE >= 5;