-- Write your PostgreSQL query statement below
WITH BASE AS (
SELECT
    PLAYER_ID,
    EVENT_DATE,
    ROW_NUMBER() OVER (PARTITION BY PLAYER_ID ORDER BY EVENT_DATE) AS RN
FROM
    ACTIVITY
)
SELECT
    PLAYER_ID,
    EVENT_DATE AS FIRST_LOGIN
FROM
    BASE
WHERE
    RN = 1